--- #YAML:1.0
name:               Data-Undump
version:            0.14
abstract:           Perl extension for securely and quickly deserializing simple Data::Dumper dumps
author:
    - Yves Orton <demerphq@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::LongString:  0.15
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
