---
abstract: 'Perl extension for securely and quickly deserializing simple Data::Dumper dumps'
author:
  - 'Yves Orton <demerphq@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Undump
no_index:
  directory:
    - t
    - inc
requires:
  Test::LongString: 0.15
version: 0.15
